keybinding:
  commits:
    moveDownCommit: 'J'
    moveUpCommit: 'K'

customCommands:
  - key: "C"
    context: "files"
    description: "AI commit message"
    command: "autocommit"
    output: terminal
